### PR TITLE
Dashboard

### PR DESCRIPTION
**Pull request by ethanrowe5379**
Created two tables
SQL statements create for compliant and non compliant rules
Should be all working fine

### CODE REVIEW

**Review by DanielJakubek — APPROVED** [review]
Looks good apart from the db connection never being closed. Might want to get that sorted as soon as possible.

**Review by DJDorren19 — COMMENTED** [review]
Looks good apart from the db connection close Daniel already mentioned

**Review by DJDorren19 — APPROVED** [review]
Doing db close later - issue added

**Review by JFergus98 — APPROVED** [review]
#28
Besides from the database connection not being closed, I think this is good to be merged, Daniel has created an issue and we will deal with it later

**Pull request merged**
