### PR TITLE
Fixing further issues

### PR DESCRIPTION
**Pull request by DanielJakubek**
Fixed some issues we had:

An exception manager could not view audits for resources - they can now.
A resource was not made compliant after the review date has passed - it does happen now but the page does not automatically refresh. 
The user can only view data related to their company and not all the data on the database like previously.
Fixed some formatting with exception tables.
Suspending an exception did not create and audit, it does now.

Changed the nav bar on all the dashboard to look a bit nicer.

### CODE REVIEW

**Review by DJDorren19 — APPROVED** [review]
The code looks good to me. Had a look at the nav bar on an old local version and looks good. No issues were spotted on review of the code.

**Review by JFergus98 — CHANGES_REQUESTED** [review]
I got an error when testing:

Fatal error: Call to undefined function str_contains() in C:\websites\2021-ac32006\JamieFergus\IndustrialTeamProject\Brightsolid_Project_Server(Testing)\ManagerDashboard.php on line 677

**Review by JFergus98 — CHANGES_REQUESTED** [review]
When viewing the audits for a resource you cannot close it plus it darkens the whole screen
image

**Review by JFergus98 — APPROVED** [review]
Turns out it was caused by my cache, I approve

**Review by JohnHarrow — APPROVED** [review]
Looks good to me

**Review by ethanrowe5379 — APPROVED** [review]
I Dont see any problems
Thought the code is starting to get messy so might be best to start putting the php into separate files
More testing will need to be done to make sure everything is good
Otherwise i approve

**Pull request merged**
