### PR TITLE
Initialise database

### PR DESCRIPTION
**Pull request by JFergus98**
Pushing the updated database scripts into the development branch:

- the changes made to the createDatabaseScript
- the testInsert Script - a cript to insert data manually
- the csvInsert script for loading the data from the csv files

### CODE REVIEW

**Review by JohnHarrow — APPROVED** [review]
Looks good to me

**Comment by ethanrowe5379** [comment]
Everything works as intended
Just the final insert within the non-compliance table doesn't work due to it being a joining table
but otherwise Good!

**Review by DJDorren19 — APPROVED** [review]
Looks good

**Review by ethanrowe5379 — APPROVED** [review]
Everything works as intended
Just the final insert within the non-compliance table doesn't work due to it being a joining table
but otherwise Good!

**Pull request merged**
