### PR TITLE
Adding buttons

### PR DESCRIPTION
**Pull request by ethanrowe5379**
Added the final bits to the branch
should be working but I tested via the Silva database
Made one modification to the exceptions in Rule 4 but that's it

### CODE REVIEW

**Review by DanielJakubek — APPROVED** [review]
Everything looks appropriate, apart from the redirect after suspending but can be easily changed after the merge - will just change the location to manager dashboard instead of Index page

**Review by JFergus98 — APPROVED** [review]
Looks good to me

**Review by DJDorren19 — APPROVED** [review]
Looks good to me

**Review by JohnHarrow — APPROVED** [review]
Looks fine to me

**Pull request merged**
